VIRTUAL_WIDTH = 224
VIRTUAL_HEIGHT = 256

WINDOW_WIDTH = VIRTUAL_WIDTH * 3
WINDOW_HEIGHT = VIRTUAL_HEIGHT * 3

DRONE_SPEED = 200
PROJECTILE_SPEED = 120
PROJECTILE_LENGTH = 4
PROJECTILE_WIDTH = 4

ROCK_WIDTH = 16
ROCK_HEIGHT = 16

BOSS_WIDTH = 50
BOSS_HEIGHT = 30

BUOY_SPEED = 30
CRAB_SPEED = 30
BUG_SPEED = 30
ROCK_SPEED = 30
TURTLE_SPEED = 30
OCTOPUS_SPEED = 30
BOSS_SPEED = 30

background_spd = 30
BACKGROUND_LOOPING_POINT = 400

background = love.graphics.newImage('graphics/background.png')
background_y = 0
scrolling = true